import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "AI Security Incident Response", description: "Operator guidance for detecting, investigating, containing, eradicating, and recovering from AI and LLM incidents." };

const scenarios = [
  ["01", "Prompt injection & tool abuse", "Untrusted input overrides intended behavior or drives a tool beyond the user's authorized task."],
  ["02", "Sensitive-data disclosure", "Prompts, retrieval, memory, logs, or model output expose protected data to the wrong identity or destination."],
  ["03", "Agent compromise", "An agent identity, runtime, memory, connector, or delegated credential is controlled or persistently influenced."],
  ["04", "Poisoned knowledge sources", "A retrieval source, embedding pipeline, index, or cached artifact is manipulated to influence decisions."],
  ["05", "Model / API credential compromise", "A model-provider key, service token, or delegated credential is exposed or used outside its expected context."],
  ["06", "Excessive agency", "The system can plan or act with broader tools, permissions, duration, or autonomy than the approved risk boundary."],
  ["07", "Malicious model or tool behavior", "A model, plugin, MCP server, dependency, or downstream tool returns deceptive output or performs hidden actions."],
];
const evidence = [
  ["Inputs", "Prompts, responses, system/developer instructions, attachments, and safety or policy output."],
  ["Runtime", "Model/provider and version, parameters, agent definition, session state, memory, and release identifiers."],
  ["Actions", "Tool calls and results, agent traces, retries, approvals, queue events, and target-system audit records."],
  ["Retrieval", "Queries, retrieved chunks, source/version identifiers, ranking, filters, embeddings metadata, and index changes."],
  ["Identity", "Users, service principals, delegated credentials, token exchanges, authorization decisions, roles, and policy versions."],
  ["Data access", "Model/API activity, connector access, read/write events, egress destinations, and relevant application or cloud logs."],
];
const phases = [
  ["01", "Investigate", "Freeze versions and build a UTC timeline across identity, instructions, memory, retrieval, tools, and downstream systems.", "Affected identities, actions, data, destinations, and earliest known influence are bounded—or uncertainty is explicitly accepted."],
  ["02", "Contain", "Pause new runs; deny write-capable tools; revoke the narrowest affected credentials; quarantine poisoned sources; preserve telemetry.", "Unsafe actions and data egress are stopped, evidence remains available, and business impact is understood."],
  ["03", "Eradicate", "Remove injected or poisoned content, rebuild compromised components, rotate exposed secrets, and close the failed authorization path.", "The demonstrated attack path no longer succeeds in isolation and no persistence mechanism remains."],
  ["04", "Recover", "Restore read-only capability first, then low-impact writes, then privileged actions with explicit approval and enhanced monitoring.", "Security and service owners approve residual risk, rollback triggers, monitoring window, and accountable operator."],
];

export default function AISecurityIR() { return <main className="guide-page"><header className="site-header"><Link className="brand" href="/"><span className="brand-mark">LR</span><span>INFOSEC<span className="brand-dot">.</span>LAB</span></Link><nav><Link href="/IncidentResponse/">Framework</Link><Link href="/#playbooks">Playbooks</Link><Link href="/ai-security-ir">AI Security IR</Link><Link href="/repository-compromise">Repository IR</Link></nav><Link className="header-cta" href="/">Back to lab ↗</Link></header><section className="guide-hero"><p className="eyebrow"><span className="live-dot"/>OPERATIONAL CAPABILITY · AI-IR</p><h1>AI Security Incident Response</h1><p className="dek">A field framework for incidents where models, agents, retrieval systems, identities, and tools can turn a bad instruction into a real downstream action.</p><div className="guide-nav"><a href="#scenarios">Scenarios</a><a href="#telemetry">Telemetry &amp; evidence</a><a href="#procedure">Response procedure</a><a href="#playbook">15-minute playbook</a></div></section><div className="guide-content">
  <section className="guide-section" id="scenarios"><h2>What counts as an AI incident</h2><p className="intro">Escalate when AI-enabled behavior crosses a confidentiality, integrity, availability, safety, or authorization boundary—not merely because an answer is surprising.</p><div className="scenario-grid">{scenarios.map(([n,title,text])=><article className="scenario-card" key={title}><small>SCENARIO / {n}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="guide-section" id="telemetry"><h2>Telemetry and evidence</h2><p className="intro">Preserve the control-plane and target-system record. A conversation transcript alone omits tool arguments, retries, policy evaluations, retrievals, and hidden downstream effects.</p><div className="evidence-grid">{evidence.map(([title,text],i)=><article className="evidence-card" key={title}><small>EVIDENCE / {String(i+1).padStart(2,"0")}</small><h3>{title}</h3><p>{text}</p></article>)}</div><div className="callout"><strong>Evidence rule:</strong> export immutably, record collection time and source, hash when chain of custody matters, restrict access, and set a purpose-based retention decision. Avoid collecting unrelated user content.</div></section>
  <section className="guide-section" id="procedure"><h2>Investigate → contain → eradicate → recover</h2><p className="intro">The phases are iterative. New indicators can send the team back to containment. Every transition has an explicit decision gate and a documented owner.</p><div className="phase-grid">{phases.map(([n,title,text,gate])=><article className="phase-card" key={title}><small>PHASE / {n}</small><h3>{title}</h3><p>{text}</p><div className="gate"><strong>Decision gate.</strong> {gate}</div></article>)}</div><div className="callout"><strong>Rollback safeguard:</strong> define the last known-good model, prompt, policy, retrieval index, tool allowlist, and credentials before recovery. Use canaries and kill switches; never roll forward if telemetry is incomplete.</div></section>
  <section className="playbook-box" id="playbook"><p className="eyebrow">AI-IR-01 · FIRST 15 MINUTES</p><h2>AI / LLM incident playbook</h2><ol><li><strong>Declare and own.</strong> Assign an incident commander, severity, scribe, and UTC start time.</li><li><strong>Stop unsafe agency.</strong> Pause new runs or queues and deny write-capable or high-impact tools. Do not delete prompts, memory, traces, or indexes.</li><li><strong>Preserve active state.</strong> Snapshot instructions, model/version, agent configuration, policy, retrievals, memory, tool transcripts, identities, and target logs.</li><li><strong>Bound identity and reach.</strong> Map users, service principals, delegated tokens, reachable tools, data stores, and external destinations.</li><li><strong>Revoke and quarantine.</strong> Rotate potentially exposed model/API credentials and isolate poisoned sources, compromised agents, connectors, or tools.</li><li><strong>Verify downstream actions.</strong> Confirm actual reads, writes, messages, transactions, deployments, and egress in authoritative target logs.</li><li><strong>Set the next gate.</strong> Name the evidence needed before eradication, rollback point, recovery test, and approver.</li></ol><p><Link className="button ghost" href="/articles/responding-to-agent-incidents">Read the detailed agent investigation note →</Link></p></section>
</div></main>; }
