import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = { title: "Responder Resources", description: "Downloadable incident-response templates for timelines, evidence, containment, credentials, AI runtime state, and recovery approval." };
const downloads = [
  ["CSV", "Incident timeline", "Record authoritative UTC events, sources, confidence, decisions, and owners.", "/templates/incident-timeline.csv"],
  ["CSV", "Evidence inventory", "Track collection source, integrity, custody, access, retention, and storage.", "/templates/evidence-inventory.csv"],
  ["MD", "Containment decision record", "Document alternatives, operational impact, evidence, approval, and rollback.", "/templates/containment-decision-record.md"],
  ["CSV", "Credential rotation register", "Coordinate revocation and replacement without recording secret values.", "/templates/credential-rotation-register.csv"],
  ["YAML", "AI runtime snapshot", "Preserve model, prompt, agent, identity, retrieval, policy, tool, and trace state.", "/templates/ai-runtime-snapshot.yaml"],
  ["MD", "Recovery authorization", "Require security and service evidence, monitoring, staged restoration, and rollback ownership.", "/templates/recovery-authorization.md"],
];
export default function Resources(){return <main className="guide-page"><header className="site-header"><Link className="brand" href="/" aria-label="LR InfoSec home"><span className="brand-mark">LR</span><span>INFOSEC<span className="brand-dot">.</span>LAB</span></Link><nav aria-label="Primary navigation"><Link href="/">Home</Link><Link href="/IncidentResponse/">Framework</Link><Link href="/#playbooks">Playbooks</Link><Link href="/ai-security-ir">AI Security IR</Link><Link href="/editorial-policy">Editorial policy</Link></nav><Link className="header-cta" href="/">Back to lab ↗</Link></header><section className="guide-hero"><p className="eyebrow"><span className="live-dot"/>RESPONDER RESOURCES</p><h1>Working artifacts for the incident</h1><p className="dek">Small, editable templates designed to capture evidence and decisions while the response is moving. Adapt fields, authorities, retention, and legal requirements before an incident.</p></section><div className="guide-content"><section className="guide-section"><h2>Download and adapt</h2><p className="intro">These files intentionally contain no automation, macros, remote content, or third-party JavaScript. Do not place secret values in the credential register.</p><div className="download-grid">{downloads.map(([format,title,desc,href])=><a className="download-card" href={href} download key={title}><small>{format} / EDITABLE TEMPLATE</small><h3>{title}</h3><p>{desc}</p><span>Download {format} ↓</span></a>)}</div></section><section className="guide-section"><h2>Use them safely</h2><ul className="operator-list"><li>Assign an owner and authoritative UTC time source before collection begins.</li><li>Store incident records in a protected repository with least privilege, retention, and access logging.</li><li>Record references to secrets and credentials—never plaintext secret values.</li><li>Hash evidence exports where integrity or chain of custody matters.</li><li>Have legal, privacy, safety, regulatory, and business owners approve organization-specific fields.</li><li>Test every template during a tabletop and revise it when responders cannot use it under pressure.</li></ul></section></div></main>}
