import Link from "next/link";
import type { Metadata } from "next";
import { GuideProvenance } from "../components/GuideProvenance";

export const metadata: Metadata = { title: "Secure Repository-Compromise Response", description: "Evidence-led response guidance for compromised source repositories, workflows, dependencies, commits, and credentials." };

const surfaces = [
  ["Code & history", "Malicious commits, rewritten history, branches, tags, releases, binaries, generated files, submodules, and visibility changes."],
  ["Workflows & delivery", "Workflow changes and runs, reusable workflows, action references, environments, artifacts, caches, deployments, and runners."],
  ["Dependencies", "Manifest and lockfile changes, install scripts, registries, compromised packages, dependency confusion, and unpinned actions."],
  ["Credentials", "Repository, environment and organization secrets; PATs; SSH and deploy keys; app tokens; cloud, registry, signing, and CI credentials."],
  ["Persistence", "New webhooks, deploy keys, collaborators, teams, apps, OAuth grants, runners, branch bypasses, ruleset changes, and executables."],
  ["Downstream impact", "Published packages, releases, deployments, images, provenance, clones, forks, mirrors, and systems reachable by exposed credentials."],
];

export default function RepositoryCompromise() { return <main className="guide-page"><header className="site-header"><Link className="brand" href="/"><span className="brand-mark">LR</span><span>INFOSEC<span className="brand-dot">.</span>LAB</span></Link><nav><Link href="/IncidentResponse/">Framework</Link><Link href="/#playbooks">Playbooks</Link><Link href="/ai-security-ir">AI Security IR</Link><Link href="/repository-compromise">Repository IR</Link></nav><Link className="header-cta" href="/">Back to lab ↗</Link></header><section className="guide-hero"><p className="eyebrow"><span className="live-dot"/>OPERATIONAL PLAYBOOK · IR-05</p><h1>Secure repository-compromise response</h1><p className="dek">Preserve the record, stop active execution, find every persistence path, restore from trusted state, and prove remediation before normal development resumes.</p><div className="guide-nav"><a href="#preserve">Preserve</a><a href="#investigate">Investigate</a><a href="#remediate">Remediate</a><a href="#validate">Validate</a></div></section><div className="guide-content">
  <section className="guide-section" id="preserve"><h2>Preserve before cleanup</h2><p className="intro">Record investigation decisions and collect evidence before destructive remediation, except when an active path must be stopped immediately.</p><ul className="checklist"><li>Export audit logs, workflow logs, artifacts, deployment records, and security alerts.</li><li>Save suspicious files, commits, diffs, refs, releases, screenshots, and query results.</li><li>Record repository, organization, actor, token, IP, timestamp, branch, and environment.</li><li>Hash exports and track collector, source, time, storage location, and access.</li><li>Preserve deleted-run and configuration-change events where available.</li><li>Maintain hypotheses, indicators, scope decisions, containment actions, and approvals.</li></ul></section>
  <section className="guide-section" id="investigate"><h2>Audit every execution and persistence surface</h2><div className="scenario-grid">{surfaces.map(([title,text],i)=><article className="scenario-card" key={title}><small>SURFACE / {String(i+1).padStart(2,"0")}</small><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="guide-section" id="remediate"><h2>Contain and remediate with gates</h2><div className="phase-grid"><article className="phase-card"><small>GATE / 01</small><h3>Stop active harm</h3><p>Revoke exploited credentials; disable malicious workflows, runners, webhooks, apps, deployments, refs, or packages.</p><div className="gate">Choose the least destructive action that stops execution. Preserve a copy before deletion whenever safe.</div></article><article className="phase-card"><small>GATE / 02</small><h3>Remove persistence</h3><p>Restore rules and access, remove unauthorized integrations, rebuild runners, audit dependencies, and reinstall trusted pinned versions.</p><div className="gate">Search every discovered indicator across all in-scope repositories and organizations.</div></article><article className="phase-card"><small>GATE / 03</small><h3>Rotate exposure</h3><p>Treat potentially exposed credentials as compromised, including signing, cloud, registry, CI, repository, environment, and organization secrets.</p><div className="gate">Revoke old material, update every consumer, test replacements, and retain proof without recording secret values.</div></article></div></section>
  <section className="guide-section" id="validate"><h2>Validate before reopening</h2><ul className="checklist"><li>Compare code, workflows, dependencies, releases, and configuration to a trusted baseline.</li><li>Rebuild artifacts and runners from trusted sources; do not reuse suspect caches.</li><li>Run code scanning and resolve incident-relevant findings.</li><li>Run secret scanning across current content and history; rotate first, then resolve alerts.</li><li>Review dependency and malware advisories; reinstall and pin reviewed dependencies.</li><li>Confirm rulesets, branch protection, least-privilege workflow permissions, environments, and reviews.</li><li>Monitor logs, workflows, deployments, API activity, and alerts through a defined observation window.</li><li>Document root cause, affected consumers, residual risk, recovery approval, and owners.</li></ul><div className="callout"><strong>Recovery gate:</strong> resume normal development only when the attack path is closed, credentials are rotated, persistence is absent, trusted builds pass, scans are reviewed, and accountable owners approve residual risk.</div><p className="source-note">Control mapping: GitHub&apos;s official <a href="https://docs.github.com/en/code-security/tutorials/secure-your-organization/respond-to-a-security-incident" rel="noopener noreferrer">security incident response guidance</a> and <a href="https://docs.github.com/en/code-security/reference/security-incident-response/investigation-areas" rel="noopener noreferrer">incident investigation areas</a>. Feature availability depends on plan and pre-incident configuration.</p></section>
  <GuideProvenance code="IR-05" standards={["GitHub security incident response guidance", "NIST SP 800-61 Rev. 3", "SLSA supply-chain integrity concepts", "MITRE ATT&CK software supply-chain techniques"]} assumptions={["Repository, organization, workflow, identity, package, and deployment records were retained before the incident.", "Responders can revoke credentials and stop workflows without erasing the investigation record."]} limitations={["GitHub security features and audit events vary by plan, role, enablement, and retention configuration.", "Repository remediation does not by itself prove downstream packages, deployments, clones, mirrors, or consumers are clean."]}/>
</div></main>; }
